### ISSUE TITLE
Include current versions and how to include in your project in Readme

### ISSUE THREAD

**Issue by calvinbrown085** [compstak/KafkaStreams4s#21]
Hi! I'm looking at using this project this morning and I didn't see anything on the Readme.

Happy to add this 😄

**Comment by pedrofurla** [comment]
For the moment would you mind using the SBT dependencies show in https://search.maven.org/search?q=kafka-streams4s after clicking in one of the artifacts ? I pinged Luka and Paul, but this project is moving fast at moment.

**Comment by pedrofurla** [comment]
Couldn't resist and made https://github.com/compstak/KafkaStreams4s/pull/22, not perfect but it will have to fill the gap until we make proper docs.

**Comment by calvinbrown085** [comment]
@pedrofurla Yep! That's how I found them this morning!
