### ISSUE TITLE
Module for Vulcan Codec

### ISSUE THREAD

**Issue by zmccoy** [compstak/KafkaStreams4s#36]
Would there be interest in a Vulcan(https://github.com/fd4s/vulcan) `Codec` for KafkaStreams4s?  I have this in a branch right now locally where I was just fooling around to understand a few things and would be open to figuring out the right ergonomics of it / getting it available.

**Comment by LukaJCB** [comment]
Yeah, please PR it!

**Comment by zmccoy** [comment]
Fixed with #39
